server:
  port: 8970

spring:
 application:
    name: flow-client-demo
 profiles:
    active: dev
 thymeleaf:
    cache: false 
    mode: HTML5  
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    prefix: classpath:/templates/
    suffix: .html 

Monitor:
   type: dev
   

logging:
  level:   
     com.sky: debug
