server:
  port: 8800
spring:
  application:
    name: demo_client
  profiles:
    active: dev
  thymeleaf:
    cache: false 
    mode: HTML5  
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/crawle?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: temp
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10 #指定连接池最大的空闲连接数量.
    max-wait: 10000 #指定连接池等待连接返回的最大等待时间，毫秒单位.
    min-idle: 5 #指定必须保持连接的最小值(For DBCP and Tomcat connection pools)
    initial-size: 5 #指定启动连接池时，初始建立的连接数量
    validation-query: SELECT 1 #指定获取连接时连接校验的sql查询语句.
    test-on-borrow: false #获取连接时候验证，会影响性能
    test-while-idle: true #当连接空闲时，是否执行连接测试.
    time-between-eviction-runs-millis: 18800 

mybatis:
  mapper-locations: classpath:com/sky/demo/mapper/*.xml
Monitor:
   type: dev
sky:
   client:
      config:
         location: http://127.0.0.1:9000
         profile: test
         enablelimit: true
         version: 1.0.0

logging:
  level:   
     com.sky: debug