server:
  port: 8900

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sky5274/cloudCenter.git
          search-paths:   config-server
          username: tianlianyouren@163.com
          password: wangfan5274
      label: master
  


  