server:
  port: 8990

spring:
  application:
    name: crawle-config
  thymeleaf:
    cache: false 
    mode: HTML5  
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    prefix: classpath:/templates/
    suffix: .html 
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/crawle?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: temp
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/cRawl/data/*/mapper/*.xml
  
logging:
  level:   
     com.crawl.data: debug
     com.sky: debug