server:
  port: 8950

spring:
 application:
    name: flow-config
 profiles:
    active: dev
 datasource:
    name: test
    url: jdbc:mysql://localhost:3306/flow?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: temp
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10 #指定连接池最大的空闲连接数量.
    max-wait: 10000 #指定连接池等待连接返回的最大等待时间，毫秒单位.
    min-idle: 5 #指定必须保持连接的最小值(For DBCP and Tomcat connection pools)
    initial-size: 5 #指定启动连接池时，初始建立的连接数量
    validation-query: SELECT 1 #指定获取连接时连接校验的sql查询语句.
    test-on-borrow: false #获取连接时候验证，会影响性能
    test-while-idle: true #当连接空闲时，是否执行连接测试.
    time-between-eviction-runs-millis: 18800 
    
mybatis:
  mapper-locations: classpath:com/sky/flow/mapper/*.xml
  type-handlers-package: com.sky.flow.typehandler
Monitor:
   type: dev
   

logging:
  level:   
     com.sky: debug
